### ISSUE TITLE
compilation errors for openmm 7.5

### ISSUE THREAD

**Issue by ajsilveira** [openmm/openmmexampleplugin#19]
I am trying to compile the plugin for openmm 7.5, but I am getting "undefined reference" errors (please see below). I was able to compile with openmm 7.2.1. Is there a version more recent than 7.2.1 for which the plugin will work? Is there something I could do to make it work for the 7.5 version? Thanks!
```
Scanning dependencies of target TestSerializeExampleForce
[ 27%] Building CXX object serialization/tests/CMakeFiles/TestSerializeExampleForce.dir/TestSerializeExampleForce.cpp.o
Linking CXX executable TestSerializeExampleForce
CMakeFiles/TestSerializeExampleForce.dir/TestSerializeExampleForce.cpp.o: In function `testSerialization()':
/home/silveira/openmmexampleplugin/serialization/tests/TestSerializeExampleForce.cpp:63: undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
/home/silveira/openmmexampleplugin/serialization/tests/TestSerializeExampleForce.cpp:69: undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
/home/silveira/openmmexampleplugin/serialization/tests/TestSerializeExampleForce.cpp:70: undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
/home/silveira/openmmexampleplugin/serialization/tests/TestSerializeExampleForce.cpp:71: undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
/home/silveira/openmmexampleplugin/serialization/tests/TestSerializeExampleForce.cpp:72: undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
CMakeFiles/TestSerializeExampleForce.dir/TestSerializeExampleForce.cpp.o: In function `void OpenMM::XmlSerializer::serialize<ExamplePlugin::ExampleForce>(ExamplePlugin::ExampleForce const*, std::string const&, std::ostream&)':
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/include/openmm/serialization/XmlSerializer.h:60: undefined reference to `OpenMM::SerializationNode::setName(std::string const&)'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/include/openmm/serialization/XmlSerializer.h:62: undefined reference to `OpenMM::SerializationNode::hasProperty(std::string const&) const'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/include/openmm/serialization/XmlSerializer.h:63: undefined reference to `OpenMM::SerializationProxy::getTypeName() const'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/include/openmm/serialization/XmlSerializer.h:64: undefined reference to `OpenMM::SerializationProxy::getTypeName() const'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/include/openmm/serialization/XmlSerializer.h:64: undefined reference to `OpenMM::SerializationNode::setStringProperty(std::string const&, std::string const&)'
../../libExamplePlugin.so: undefined reference to `OpenMM::SerializationNode::createChildNode(std::string const&)'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
../../libExamplePlugin.so: undefined reference to `OpenMM::SerializationProxy::SerializationProxy(std::string const&)'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
../../libExamplePlugin.so: undefined reference to `OpenMM::SerializationNode::setDoubleProperty(std::string const&, double)'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::copy(char*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'
../../libExamplePlugin.so: undefined reference to `OpenMM::SerializationNode::setIntProperty(std::string const&, int)'
../../libExamplePlugin.so: undefined reference to `OpenMM::SerializationNode::getDoubleProperty(std::string const&) const'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
../../libExamplePlugin.so: undefined reference to `OpenMM::SerializationNode::getIntProperty(std::string const&) const'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
../../libExamplePlugin.so: undefined reference to `OpenMM::Platform::createKernel(std::string const&, OpenMM::ContextImpl&) const'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
../../libExamplePlugin.so: undefined reference to `OpenMM::SerializationNode::getChildNode(std::string const&) const'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0-py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
make[2]: *** [serialization/tests/TestSerializeExampleForce] Error 1
make[1]: *** [serialization/tests/CMakeFiles/TestSerializeExampleForce.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by peastman** [comment]
This looks to me like an ABI inconsistency.  It looks like you have a build of OpenMM that was compiled with the old (pre-C++11) ABI, and you're compiling the plugin with the new ABI.  Can you try using the [OpenMM 7.5 beta](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=12332&p=0&start=0&view=&sid=126e2b5f6a9ca0d2850e75963c415bbb)?  I *think* that uses the modern ABI.

**Comment by ajsilveira** [comment]
I am getting the same errors (please see below). I was able to compile with an older version of OpenMM (7.2.1) The gcc version I am using is 4.8.5 . Thanks!

```
[ 27%] Building CXX object serialization/tests/CMakeFiles/TestSerializeExampleForce.dir/TestSerializeExampleForce.cpp.o
Linking CXX executable TestSerializeExampleForce
CMakeFiles/TestSerializeExampleForce.dir/TestSerializeExampleForce.cpp.o: In function `testSerialization()':
/home/silveira/openmmexampleplugin/serialization/tests/TestSerializeExampleForce.cpp:63: undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
/home/silveira/openmmexampleplugin/serialization/tests/TestSerializeExampleForce.cpp:69: undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
/home/silveira/openmmexampleplugin/serialization/tests/TestSerializeExampleForce.cpp:70: undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
/home/silveira/openmmexampleplugin/serialization/tests/TestSerializeExampleForce.cpp:71: undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
/home/silveira/openmmexampleplugin/serialization/tests/TestSerializeExampleForce.cpp:72: undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
CMakeFiles/TestSerializeExampleForce.dir/TestSerializeExampleForce.cpp.o: In function `void OpenMM::XmlSerializer::serialize<ExamplePlugin::ExampleForce>(ExamplePlugin::ExampleForce const*, std::string const&, std::ostream&)':
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/include/openmm/serialization/XmlSerializer.h:60: undefined reference to `OpenMM::SerializationNode::setName(std::string const&)'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/include/openmm/serialization/XmlSerializer.h:62: undefined reference to `OpenMM::SerializationNode::hasProperty(std::string const&) const'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/include/openmm/serialization/XmlSerializer.h:63: undefined reference to `OpenMM::SerializationProxy::getTypeName() const'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/include/openmm/serialization/XmlSerializer.h:64: undefined reference to `OpenMM::SerializationProxy::getTypeName() const'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/include/openmm/serialization/XmlSerializer.h:64: undefined reference to `OpenMM::SerializationNode::setStringProperty(std::string const&, std::string const&)'
../../libExamplePlugin.so: undefined reference to `OpenMM::SerializationNode::createChildNode(std::string const&)'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
../../libExamplePlugin.so: undefined reference to `OpenMM::SerializationProxy::SerializationProxy(std::string const&)'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
../../libExamplePlugin.so: undefined reference to `OpenMM::SerializationNode::setDoubleProperty(std::string const&, double)'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::copy(char*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
../../libExamplePlugin.so: undefined reference to `OpenMM::SerializationNode::setIntProperty(std::string const&, int)'
../../libExamplePlugin.so: undefined reference to `OpenMM::SerializationNode::getDoubleProperty(std::string const&) const'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
../../libExamplePlugin.so: undefined reference to `OpenMM::SerializationNode::getIntProperty(std::string const&) const'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
../../libExamplePlugin.so: undefined reference to `OpenMM::Platform::createKernel(std::string const&, OpenMM::ContextImpl&) const'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()@GLIBCXX_3.4.26'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
../../libExamplePlugin.so: undefined reference to `OpenMM::SerializationNode::getChildNode(std::string const&) const'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/home/silveira/miniconda3/pkgs/openmm-7.5.0b1-cc3c4b5_py36_cuda102_debug_0/lib/libOpenMM.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
make[2]: *** [serialization/tests/TestSerializeExampleForce] Error 1
make[1]: *** [serialization/tests/CMakeFiles/TestSerializeExampleForce.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ajsilveira** [comment]
@peastman I was able to compile the plugin by specifying a more recent version of the gcc compiler. Thanks!
